### PR TITLE
Add simple github workflow to check if lib compiles against latest Ubuntu target

### PR DESCRIPTION
**Pull request by BennyKJohnson**
There is more efficient ways of performing this check but it's a start. Also more platforms can be added in the future.

### CODE REVIEW

**Comment by hmelder** [comment]
Great Idea! I don't quite understand why you opted to use libs-corebase instead of libs-base. Maybe we could use the libs-base workflow configuration as a reference.

**Comment by hmelder** [comment]
> Great Idea! I don't quite understand why you opted to use libs-corebase instead of libs-base. Maybe we could use the libs-base workflow configuration as a reference.

Nevermind, just saw the gnustep-web-install reference :)

**Comment by hmelder** [comment]
https://github.com/BennyKJohnson/libs-opal/runs/8000285726?check_suite_focus=true

The installation of libs-corebase fails.

**Comment by BennyKJohnson** [comment]
@hmelder I've added sudo to the command. Could you please attempt another run for me.

**Comment by hmelder** [comment]
Still failing... Try `make` and then `sudo make install`

https://github.com/BennyKJohnson/libs-opal/runs/8168610264?check_suite_focus=true

**Comment by BennyKJohnson** [comment]
Turns out the path env needs to be explicitly passed when using sudo. Should be good to go now https://github.com/BennyKJohnson/libs-opal/runs/8169044555?check_suite_focus=true

**Pull request merged**
