### PR TITLE
Fix Opal headers

### PR DESCRIPTION
**Pull request by theiostream**
The commits describe in more detail each of the fixes provided to the build.

### CODE REVIEW

**Comment by ivucica** [comment]
Please include updates to `ChangeLog` and I'll import this.

Thanks!

**Comment by ivucica** [comment]
Ping! Can you update `ChangeLog` (and rebase, since I added a commit since)?

**Comment by theiostream** [comment]
Hi there! So, I hacked this up from an existing script (https://gist.github.com/theiostream/8901abfd2ca595d2360b6e655f5ed77a) to convert my Git commits into changelog entries. (it's a work-in-progress, and there are still some bugs). The result is in the latest commit.

As you can notice, I have the habit of writing extensive messages in each commit (in a way that `git log` itself works as a changelog). Now that the project is using Git as the main VCS system, I wonder if we could adopt that as the "default" (or at least an acceptable) way of detailing patches (it works really well with `git blame`, other parts of the Git ecosystem and with the GitHub UI, in contrast to looking for changes in the ChangeLog).

That said, is it okay to do what I've done to the ChangeLog and just keep the commit title along with the files in it?

**Comment by theiostream** [comment]
Also, I'm sorry for having taken so long to answer. I don't get notifications from GitHub, so I only saw this when I actually came in here to check for an update.

**Comment by ivucica** [comment]
My understanding of the ChangeLog file is that it's intended to be even more human-readable than the usual VCS logs. With Subversion, there was the added value of not having to talk to the server to fetch the changelog entries. Finally, it's also a log that can be shipped in source tarballs.

While I do not use a similar file for any of my personal projects, I would not drop ChangeLog in GNUstep.

Now, having said all that, I'd suggest that you:

- do use your script 
- do consider merging distinct entries with same date into one entry, with multiple blocks of files mentioned
- do consider whether, for some entries, it's useful to also edit the entries to give a different view of the changes than just the Git commit "title" provides (maybe it isn't useful, I'm not requesting that you do it -- just consider whether it's better for some of the changes)

Finally, I consider `git amend` perfectly fine when you're updating a pull request -- do whatever makes semantic sense :)

**Comment by ivucica** [comment]
Can you update the ChangeLog or at least push back on it so we can merge this PR? Ping @theiostream

**Comment by theiostream** [comment]
@ivucica I _just_ (literally now) pushed a new try at a ChangeLog on Base. Could you see if you like the result and see if I can apply it here? (ref: https://github.com/gnustep/libs-base/pull/8/commits/ff9bc12c6482a6c081e762fc6a2bcb41e0b3c881)

It pretty much:
* Uses the current date instead of the commit date to generate entries for each commit. Otherwise, big rebases like the one in Base would have a very weird timeline.
* Does not copy the commit title into the ChangeLog. Instead, it copies the commit description (in respect to "it's intended to be even more human-readable than the usual VCS logs"). It generates a rather redundant repetition of what's in the `git log` in the changelog, but it keeps consistency with the existing changelog history;
* Does not merge same-date entries into the same one due to the rebase issue.
* The commit body should have enough detailed insight over the problem to the point that it's not an issue if the ChangeLog entry just copies it.

**Comment by ivucica** [comment]
I feel like the automation can be a good starter, but you should not shy away from editing ChangeLog manually.

Individually:

1. Looking at it, I think it's preferable if you use the actual dates when you made a change. We can thus follow your progress over time more easily when looking into ChangeLog.
1. SGTM, but depends on what the description is like, I guess. 
1. I would prefer if you merged "connected changes". Using commit dates in ChangeLog and merging same-date changes seemed like a decent workaround if you have a strong preference for automation.
1. SGTM.

Either way, I hope we can minimize the amount of bikeshedding on this topic, your other changes are much more important than the ChangeLog. :)

**Comment by ivucica** [comment]
(All that said, yes, the changelog in https://github.com/gnustep/libs-base/pull/8/commits/ff9bc12c6482a6c081e762fc6a2bcb41e0b3c881 is better.)

**Comment by theiostream** [comment]
Updated!

**Pull request merged**
